import type { Metadata } from "next";
import { Lora, Newsreader } from "next/font/google";
import "./globals.css";
import { LuBookText } from "react-icons/lu";
import Link from "next/link";

const loraFont = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const newsreaderFont = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${loraFont.variable} ${newsreaderFont.className} antialiased`}>
        <header className="border-b border-gray-200">
          <div className="grid grid-flow-col justify-between px-10 h-16 mx-auto max-w-[1440px]">
            <div className="flex items-center gap-x-2">
              <LuBookText className="text-2xl" />
              <h5 className="font-bold text-xl">
                Pustaka Salaf
              </h5>
            </div>
            <nav className="flex">
              <ul className="grid items-center grid-flow-col">
                <Link href="/">
                  <li className="px-6 py-2 rounded font-medium transition hover:bg-emerald-100">
                    Beranda
                  </li>
                </Link>
                <Link href="/daftar-buku">
                  <li className="px-6 py-2 rounded font-medium transition hover:bg-emerald-100">
                    Daftar Buku
                  </li>
                </Link>
                <Link href="/kategori">
                  <li className="px-6 py-2 rounded font-medium transition hover:bg-emerald-100">
                    Kategori
                  </li>
                </Link>
                <Link href="/koleksi">
                  <li className="px-6 py-2 rounded font-medium transition hover:bg-emerald-100">
                    Buku Koleksi
                  </li>
                </Link>
              </ul>
            </nav>

          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
